
name: Publish to Nuget

on:
  push:
    tags: 
      - "*"
    # branches: 
    #   - "main"
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy to NuGet
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v5

      - name: List files (for debugging)
        run: ls -R

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Get tag name
        run: echo "The tag name is ${{ github.ref_name }}"
        
      # - name: Pack the NuGet package
      #   run: dotnet pack --configuration Release --no-build --output .
      # - name: Push to NuGet
      #   run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
